name: shared_preferences_typed
description: A wrapper around shared_preferences to provide type safety.
version: 1.1.0
homepage: https://philippbauer.me/
repository: https://github.com/CiriousJoker/shared_preferences_typed

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ">=0.5.2 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
 uses-material-design: true